[shell]
corner_radius_scale = 0.8
font_family = "FiraMono Nerd Font Mono"

[shell.animation]
speed = 1.2

[shell.panel]
transparency_mode = "soft"
wallpaper_placement = "floating"
floating_offset = 24

[shell.launcher]
categories = false
compact = true

[keybinds]
left = ["left", "alt+h"]
right = ["right", "alt+l"]
up = ["up", "alt+k"]
down = ["down", "alt+j"]

[bar.default]
contact_shadow = true
background_opacity = 0.6
radius = 0
margin_ends = 0
concave_edge_corners = false
scale = 0.8
thickness = 28

[bar.default.dead_zone.actions]
left = "panel-toggle launcher"
middle = "exec foot"
scroll_up = "volume-up"
scroll_down = "volume-down"

[widget.active_window]
min_length = 150
max_length = 150
title_scroll = "on_hover"
show_empty_label = true

[widget.audio_visualizer]
bands = 32
mirrored = false
centered = false
show_when_idle = true
color_2 = "#fefefe"

[widget.clock]
format = "{:%F} {:%R} {:%a}"
tooltip_format = "{:%T}"

[widget.lock_keys]
display = "full"

[widget.media]
art_size = 24
title_scroll = "on_hover"

[widget.media.actions]
scroll_right = "next"
scroll_left = "previous"
scroll_up = "volume-up"
scroll_down = "volume-down"

[widget.privacy]
hide_inactive = true

[widget.cpu]
type = "sysmon"
stat = "cpu_usage"

[widget.ram]
type = "sysmon"
stat = "ram_pct"
