[include]
files = ["widgets/"]

[shell]
corner_radius_scale = 0.8
font_family = "FiraMono Nerd Font Mono"
avatar_path = "~/avatar.png"

[shell.animation]
speed = 1.2

[shell.panel]
transparency_mode = "glass"
wallpaper_placement = "floating"
floating_offset = 24
open_near_click_control_center = true
open_near_click_session = true

[shell.launcher]
categories = false
compact = true

[keybinds]
left = ["left", "alt+h"]
right = ["right", "alt+l"]
up = ["up", "alt+k"]
down = ["down", "alt+j"]

[control_center]
sidebar = "full"

[control_center.calendar]
event_date_format = "%B %e日  %A"

[location]
auto_locate = true

[notification]
background_opacity = 0.6
