[wallpaper]
fill_mode = "crop"
transition = ["fade"]
directory = "~/Wallpapers"
per_monitor_directories = true

[backdrop]
enabled = true
blur_intensity = 0.5
tint_intensity = 0.3

[theme.templates]
enable_buildin_templates = true
builtin_ids = ["foot"]
