$background = rgb(151218)
$foreground = rgb(e7e0e8)
$primary = rgb(ebdcff)
$secondary = rgb(eadef7)
$tertiary = rgb(ffd9e0)
$surface = rgb(151218)
$on_surface = rgb(e7e0e8)
$outline = rgb(948f99)
$error = rgb(ffb4ab)

$label_color = $foreground
$time_color = $primary
$date_color = $secondary
$input_color = $surface
$input_text_color = $on_surface
$border_color = "$primary
$check_color = $tertiary"
