source = ./colors-hyprlock.conf

general {
  hide_cursor = true
}

animations {
  enabled = true
  bezier = easeOutQuint, 0.23, 1, 0.32, 1
  animation = fadeIn, 1, 4, easeOutQuint
  animation = fadeOut, 1, 4, easeOutQuint
}

background {
  monitor =
  path = ~/lock_wallpaper.jpg
  blur_passes = 3
  blur_size = 6
  vibrancy = 1
}

label {
  monitor =
  text = cmd[update:1000] echo "$(date +"%H:%M")"
  
  color = $time_color
  font_size = 90
  font_family = Sans Bold

  position = 0, -200
  halign = center
  valign = top
}

label {
  monitor =
  text = cmd[update:1000] echo "$(date +"%B %d日 %A")"

  color = $date_color
  font_size = 20
  font_family = Sans

  position = 0, -380
  halign = center
  valign = top
}

image {
  monitor =
  path = ~/avatar.png
  size = 110
  rounding = -1
  border_size = 2
  
  border_color = $primary
  
  position = -140, -10
  halign = center
  valign = center
}

label {
  monitor =
  text = $USER
  
  color = $secondary
  font_size = 18
  font_family = Sans
  
  position = 10, 20
  halign = center
  halign = center
  text_align = left
}

input-field {
  monitor =
  size = 260, 48
  outline_thickness = 2
  dots_size = 0.2
  dots_spacing = 0.3
  dots_center = true
  dots_rounding = -1
  fade_on_empty = false
  
  font_color = $on_surface
  inner_color = $surface
  outer_color = $primary
  check_color = $tertiary
  fail_color = $error
  
  position = 75, -40
  halign = center
  valign = center
}

